### ISSUE TITLE
replace `es5-ext` with `core-js@^3`

### ISSUE THREAD

**Issue by bowencool** [medikoo/memoizee#123]
Error using Vite
``` 
> node_modules/memoizee/normalizers/get-1.js:3:22: error: Could not read from file: /Users/x/x/node_modules/es5-ext/array/index.js#/e-index-of
    3 │ var indexOf = require("es5-ext/array/#/e-index-of");
      ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > node_modules/d/index.js:7:30: error: Could not read from file: /Users/x/x/node_modules/es5-ext/string/index.js#/contains
    7 │   , contains        = require("es5-ext/string/#/contains");
      ╵     
```

**Comment by medikoo** [comment]
@bowencool it's scheduled to use `ext` instead of `es5-ext` under the hood. Still note that using `es5-ext` as it's currently it's perfectly right and compliant with standards.

The problem you've approached it's about a limitation on Vite site, and not an issue in this package. Have you reported it on Vite site?

**Comment by bowencool** [comment]
> @bowencool it's scheduled to use `ext` instead of `es5-ext` under the hood. Still note that using `es5-ext` as it's done currently is perfectly right and compliant with standards.
> 
> The problem you've approached it's about a limitation on Vite site, and not an issue in this package. Have you reported it on Vite site?

I found it
https://github.com/vitejs/vite/pull/2432
