### ISSUE TITLE
Memory leak when using `maxAge` on node.js

### ISSUE THREAD

**Issue by benoitkoenig** [medikoo/memoizee#142]
I have noticed that the following script causes a memory leak when executed with node.js:
```
const memoizee = require("memoizee");
const { writeHeapSnapshot } = require("v8");

const f = memoizee(function f(a) {
    return Array(10000000).fill(0);
}, {
    maxAge: 100,
});

let i = 0;

while (true) {
    f(i++);

    writeHeapSnapshot();
}
```

- I have not found a memory leak when using a similar script on chrome
- I have not found a memory leak when using `max` instead of `maxAge`

**Comment by medikoo** [comment]
@benoitkoenig I believe it's because currently `maxAge` is implemented with `setTimeout` internally, and the way you written your logic, event loop is locked, hence (here's no way `setTimeout` callbacks will be called).

This is planned to be fixed with v1, for which new internal design of this feature is proposed, see https://github.com/medikoo/memoizee/issues/73

Therefore we may call this a design bug, for which there's a plan to have it fixed.

Nonetheless your example is not realistic. In real world `maxAge` usage always will go in pair with asynchronicity, and not a single locked event loop, taking that into account, test case should rather be expressed as:

```javascript
const memoizee = require("memoizee");
const { writeHeapSnapshot } = require("v8");

const f = memoizee(function f(a) {
    return Array(10000000).fill(0);
}, {
    maxAge: 100,
});

let i = 0;

(function self () {
  f(++i);
  writeHeapSnapshot();
  setTimeout(self);
})();
```

**Comment by benoitkoenig** [comment]
@medikoo You're absolutely right. It's great if you have a plan to fix this, although the flaw is rather on my side.

I will rewrite my script to free the event loop once in a while. For me, this issue can be closed.
